CREATE TABLE moradores (
	id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome             VARCHAR(120) NOT NULL,
	nome_normalizado VARCHAR(120) NOT NULL,
	email            VARCHAR(255) NOT NULL,
	senha_hash       VARCHAR(100) NOT NULL,
	telefone         VARCHAR(11)  NOT NULL,
	apartamento      VARCHAR(10)  NOT NULL,
	CONSTRAINT uk_moradores_email UNIQUE (email),
	CONSTRAINT uk_moradores_apartamento_nome UNIQUE (apartamento, nome_normalizado)
);

CREATE TABLE funcionarios (
	id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome       VARCHAR(120) NOT NULL,
	email      VARCHAR(255) NOT NULL,
	senha_hash VARCHAR(100) NOT NULL,
	perfil     VARCHAR(20)  NOT NULL DEFAULT 'PORTEIRO',
	CONSTRAINT uk_funcionarios_email UNIQUE (email)
);

CREATE TABLE encomendas (
	id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	morador_id              BIGINT       NOT NULL,
	nome_destinatario       VARCHAR(120) NOT NULL,
	apartamento             VARCHAR(10)  NOT NULL,
	descricao               VARCHAR(255) NOT NULL,
	status                  VARCHAR(20)  NOT NULL,
	data_recebimento        TIMESTAMP    NOT NULL,
	porteiro_recebimento_id BIGINT       NOT NULL,
	data_notificacao        TIMESTAMP,
	data_confirmacao        TIMESTAMP,
	data_retirada           TIMESTAMP,
	porteiro_retirada_id    BIGINT,
	CONSTRAINT fk_encomendas_morador FOREIGN KEY (morador_id) REFERENCES moradores (id),
	CONSTRAINT fk_encomendas_porteiro_recebimento FOREIGN KEY (porteiro_recebimento_id) REFERENCES funcionarios (id),
	CONSTRAINT fk_encomendas_porteiro_retirada FOREIGN KEY (porteiro_retirada_id) REFERENCES funcionarios (id)
);

CREATE INDEX idx_encomendas_status ON encomendas (status);
CREATE INDEX idx_encomendas_apartamento ON encomendas (apartamento);
CREATE INDEX idx_encomendas_morador ON encomendas (morador_id);

CREATE TABLE notificacoes (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	encomenda_id    BIGINT        NOT NULL,
	morador_id      BIGINT        NOT NULL,
	destinatario    VARCHAR(255)  NOT NULL,
	assunto         VARCHAR(150)  NOT NULL,
	mensagem        VARCHAR(2000) NOT NULL,
	status          VARCHAR(20)   NOT NULL,
	data_criacao    TIMESTAMP     NOT NULL,
	data_envio      TIMESTAMP,
	data_confirmacao TIMESTAMP,
	CONSTRAINT uk_notificacoes_encomenda UNIQUE (encomenda_id),
	CONSTRAINT fk_notificacoes_encomenda FOREIGN KEY (encomenda_id) REFERENCES encomendas (id),
	CONSTRAINT fk_notificacoes_morador FOREIGN KEY (morador_id) REFERENCES moradores (id)
);

CREATE INDEX idx_notificacoes_morador ON notificacoes (morador_id);
